Data cleaning, Data integration, Data transformation, Data model building

# Importing Libraries

In [ ]:
import pandas as pd
import numpy as np

# Importing Dataset

In [ ]:
dataset = pd.read_csv('train.csv')

# Data Describe

In [ ]:
dataset.describe()

,TransactionID,FraudLabel,CardSecurityCode,D1,D2,D3,D4,D5,D10,D11,...,V283,V289,V290,V302,V303,V304,V312,V313,V314,V315
count,9.000000e+04,90000.000000,89765.000000,89787.000000,45462.000000,48692.000000,64164.000000,43233.000000,77730.000000,44758.000000,...,89787.000000,89787.000000,89998.000000,89998.000000,89998.000000,89998.000000,89998.000000,89787.000000,89787.000000,89787.000000
mean,3.283457e+06,0.150000,154.284989,86.187522,158.739915,26.332539,131.458653,38.542895,115.179609,140.965906,...,1.104013,0.251417,1.126347,0.292895,0.333752,0.308907,43.079435,23.231223,46.424193,29.679078
std,1.695498e+05,0.357073,12.600792,151.142154,173.434898,60.340088,186.767625,85.294921,178.242860,183.619065,...,1.832747,0.627080,0.942225,0.512858,0.674170,0.564486,192.937788,98.807304,179.089794,123.881791
min,2.987002e+06,0.000000,100.000000,0.000000,0.000000,0.000000,-53.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,3.139412e+06,0.000000,150.000000,0.000000,20.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,3.282971e+06,0.000000,150.000000,1.000000,86.000000,7.000000,17.000000,7.000000,7.000000,36.000000,...,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,3.428914e+06,0.000000,150.000000,103.000000,252.000000,25.000000,228.000000,29.000000,172.000000,259.000000,...,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000
max,3.577531e+06,1.000000,231.000000,640.000000,640.000000,692.000000,864.000000,731.000000,855.000000,670.000000,...,68.000000,9.000000,60.000000,15.000000,20.000000,15.000000,30250.000000,4079.939941,6159.890137,4489.850098

# Data information

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90000 entries, 0 to 89999
Columns: 126 entries, TransactionID to V315
dtypes: float64(111), int64(2), object(13)
memory usage: 86.5+ MB

In [ ]:
dataset.head()

,TransactionID,FraudLabel,ProductCategory,CardSecurityCode,CardType,CardUsageType,PrimaryEmailDomain,D1,D2,D3,...,V283,V289,V290,V302,V303,V304,V312,V313,V314,V315
0,3324111,0,W,150.0,visa,debit,yahoo.com,47.0,47.0,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,117.0,0.0,112.0,0.0
1,3030057,1,R,150.0,visa,debit,gmail.com,0.0,NaN,NaN,...,1.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0
2,3387080,0,W,150.0,mastercard,credit,gmail.com,0.0,NaN,NaN,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,3441177,0,W,150.0,mastercard,debit,yahoo.com,12.0,12.0,0.0,...,1.0,1.0,1.0,0.0,0.0,0.0,117.0,117.0,234.0,117.0
4,3397229,0,W,150.0,mastercard,credit,gmail.com,136.0,136.0,75.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
dataset.tail()

,TransactionID,FraudLabel,ProductCategory,CardSecurityCode,CardType,CardUsageType,PrimaryEmailDomain,D1,D2,D3,...,V283,V289,V290,V302,V303,V304,V312,V313,V314,V315
89995,3380095,1,C,185.0,visa,credit,gmail.com,0.0,NaN,NaN,...,1.0,0.0,1.0,1.0,1.0,1.0,0.0000,0.0000,0.0000,0.0000
89996,3528118,0,C,185.0,visa,debit,gmail.com,0.0,0.0,0.0,...,3.0,1.0,3.0,1.0,1.0,1.0,7.6405,7.6405,7.6405,7.6405
89997,3171473,0,W,150.0,visa,debit,ymail.com,106.0,106.0,10.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0000,0.0000,0.0000,0.0000
89998,3136223,1,C,185.0,visa,credit,gmail.com,71.0,NaN,71.0,...,0.0,0.0,1.0,1.0,1.0,1.0,0.0000,0.0000,0.0000,0.0000
89999,3109146,0,W,150.0,visa,debit,gmail.com,0.0,NaN,NaN,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0000,0.0000,0.0000,0.0000

# Checking null values

In [ ]:
dataset.isnull().sum()

TransactionID         0
FraudLabel            0
ProductCategory       0
CardSecurityCode    235
CardType            235
                   ...
V304                  2
V312                  2
V313                213
V314                213
V315                213
Length: 126, dtype: int64

# For feeling null values

In [ ]:

threshold = 0.5 * len(dataset)
dataset_1 = dataset.dropna(thresh=threshold, axis=1)


dataset_1.fillna(dataset_1.mean(numeric_only=True), inplace=True)

<ipython-input-91-9d3daa3e6ae3>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset_1.fillna(dataset_1.mean(numeric_only=True), inplace=True)

# Dropping columns which are not required

In [ ]:
columns_to_drop = ["TransactionID", "CardSecurityCode", "PrimaryEmailDomain"]
dataset_1.drop(columns=[col for col in columns_to_drop if col in dataset_1.columns], inplace=True)

<ipython-input-92-85cee117716f>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset_1.drop(columns=[col for col in columns_to_drop if col in dataset_1.columns], inplace=True)

In [ ]:
dataset_1.isnull().sum()

FraudLabel           0
ProductCategory      0
CardType           235
CardUsageType      235
D1                   0
                  ...
V304                 0
V312                 0
V313                 0
V314                 0
V315                 0
Length: 113, dtype: int64

# Label Encoding

In [ ]:

dataset_1 = dataset_1.copy()
if "CardType" in dataset_1.columns:
    dataset_1["CardType"] = dataset_1["CardType"].fillna("Unknown")

if "CardUsageType" in dataset_1.columns:
    dataset_1["CardUsageType"] = dataset_1["CardUsageType"].fillna("Unknown")

if "CardSecurityCode" in dataset_1.columns:
    dataset_1["CardSecurityCode"] = dataset_1["CardSecurityCode"].fillna(0)  # Assuming numeric

In [ ]:
dataset_1.isnull().sum()

FraudLabel         0
ProductCategory    0
CardType           0
CardUsageType      0
D1                 0
                  ..
V304               0
V312               0
V313               0
V314               0
V315               0
Length: 113, dtype: int64

# Standard Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
num_cols = dataset_1.select_dtypes(include=['number']).columns
dataset_1[num_cols] = scaler.fit_transform(dataset_1[num_cols])

# Label Encoding the columns which has categorical values

In [ ]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()


for col in dataset_1.select_dtypes(include=['object']).columns:
    dataset_1[col] = label_encoder.fit_transform(dataset_1[col])

In [ ]:
dataset_1.describe()

,FraudLabel,ProductCategory,CardType,CardUsageType,D1,D2,D3,D4,D10,D15,...,V283,V289,V290,V302,V303,V304,V312,V313,V314,V315
count,9.000000e+04,90000.000000,90000.000000,90000.000000,9.000000e+04,9.000000e+04,9.000000e+04,9.000000e+04,9.000000e+04,9.000000e+04,...,9.000000e+04,9.000000e+04,9.000000e+04,9.000000e+04,9.000000e+04,9.000000e+04,9.000000e+04,9.000000e+04,9.000000e+04,9.000000e+04
mean,1.578984e-19,3.078011,3.601922,2.710889,-3.252707e-17,-2.657430e-16,-4.204045e-17,7.515963e-17,-9.868649e-18,-3.757982e-17,...,-3.702717e-17,-7.926499e-17,-1.623195e-16,1.212660e-16,9.316005e-18,3.000069e-17,-4.863270e-17,-8.810730e-17,-1.989520e-17,-3.473764e-17
std,1.000006e+00,1.529930,0.617355,0.470455,1.000006e+00,1.000006e+00,1.000006e+00,1.000006e+00,1.000006e+00,1.000006e+00,...,1.000006e+00,1.000006e+00,1.000006e+00,1.000006e+00,1.000006e+00,1.000006e+00,1.000006e+00,1.000006e+00,1.000006e+00,1.000006e+00
min,-4.200840e-01,0.000000,0.000000,0.000000,-5.709206e-01,-1.287809e+00,-5.933128e-01,-1.169705e+00,-6.953335e-01,-1.128554e+00,...,-6.030990e-01,-4.014107e-01,-1.340968e-01,-5.711142e-01,-4.950642e-01,-5.472444e-01,-2.232852e-01,-2.353965e-01,-2.595317e-01,-2.398611e-01
25%,-4.200840e-01,2.000000,3.000000,2.000000,-5.709206e-01,-6.063423e-01,-4.581235e-01,-8.336169e-01,-6.953335e-01,-8.381785e-01,...,-6.030990e-01,-4.014107e-01,-1.340968e-01,-5.711142e-01,-4.950642e-01,-5.472444e-01,-2.232852e-01,-2.353965e-01,-2.595317e-01,-2.398611e-01
50%,-4.200840e-01,4.000000,4.000000,3.000000,-5.642965e-01,-2.305767e-16,-8.004813e-17,0.000000e+00,-5.021511e-01,-3.067368e-01,...,-5.682002e-02,-4.014107e-01,-1.340968e-01,-5.711142e-01,-4.950642e-01,-5.472444e-01,-2.232852e-01,-2.353965e-01,-2.595317e-01,-2.398611e-01
75%,-4.200840e-01,4.000000,4.000000,3.000000,1.047445e-01,-2.305767e-16,-8.004813e-17,0.000000e+00,4.721131e-02,3.671533e-01,...,-5.682002e-02,-4.014107e-01,-1.340968e-01,1.378777e+00,9.882660e-01,1.224307e+00,-2.232852e-01,-2.353965e-01,-2.595317e-01,-2.398611e-01
max,2.380476e+00,4.000000,4.000000,4.000000,3.668547e+00,3.904317e+00,1.499852e+01,4.645254e+00,4.466259e+00,3.911924e+00,...,3.654387e+01,1.396791e+01,6.248467e+01,2.867726e+01,2.917154e+01,2.602603e+01,1.565656e+02,4.110567e+01,3.417697e+01,3.604632e+01

# Printing one column

In [ ]:
dataset_1['M1']

0        1
1        2
2        2
3        1
4        1
        ..
89995    2
89996    2
89997    2
89998    2
89999    0
Name: M1, Length: 90000, dtype: int64